# Generated by Django 5.0 on 2023-12-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_supercategory_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SuperCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_categories', to='product.supercategory'),
        ),
    ]
